# NumPy

İsmi [_NumPy_](https://docs.scipy.org/doc/numpy/reference/) olan bir pakete başlayacağız. Numpy ileri derece matematik yapmak için ve veri depolamak için kullanan temel bir pakettir. Bu ders boyunca Numpy kullanacağız. 

Daha önceden Numpy ‘yi yerel ağınıza kurmuş olmalısınız. Halen kurmadıysanız şimdi pip install numpy ile kurun.

Numpy’yi kurduktan sonra, paketi ortama çıkartmalıyız bu şekilde programı kullanabiliriz. İmport komutu ile bunu yapabiliriz. Paketi çıkarttığınız zaman fonksiyonları çağırmak için kısaltma kullanma şansınız olacak. Bir çok paket standard kısaltmalar kullanır. Biz de bunu takip edeceğiz. Numpy için kısaltma np dir. Kısaltmaları aşağıdaki gibi çıkartabilir ve kullanabilirsiniz. 


In [1]:
import numpy as np

Şimdi paket makinamıza kuruldu ve çevremize çıkartıldı. Numpy ile çalışmaya hazırız. 

Başlamadan önce, çıkartma komutu ile bir kod yazmak hakkında bir not yapmakta fayda var. İmport komutu komut dosyası içerisinde veya notebookta herhangi bir hücrede her yerde çalışacaktır. Fakat [Python style](https://www.python.org/dev/peps/pep-0008/#imports) komut dosyasının başında veya ilk hücrede gözükmesini istiyor. (çoğu notebook ilk hücreyi bu amaç için kullanıyor). Gerekli paketler tek bir yere kurulur ve saklanırsa onların doğrulanması kolay bir şekilde olacaktır. 



## Array

Yukarıda söylediğimiz gibi, Numpy Pythonda matematiksel verilerin saklanması ve değiştirilmesi için temel bir pakettir. Numpy bunun yeni bir veri yapısı ile başarır: diziler. 

Bir numpy dizisi, ilave matematiksel fonksiyonellikte ve özellikler ile bir Python listesi gibi düşünülebilir. Bu dizilerin en büyük özelliklerinden birisi, listeler gibi, çoklu boyuta sahip olabilir. Tek boyutlu bir dizi sıralı bir set değeri gibi çalışır, değişik veri noktaları girilir içine. Diziler index ile ulaşmak için  kapalı parantez işareti kullanır [ ], listeler veya stringslerde olduğu gibi. np.array yazarak bir dizi oluşturabiliriz. Örneğin bir liste:




In [2]:
x = np.array([0, 1, 2, 3])
x

array([0, 1, 2, 3])

Dizinize manuel olarak bir dizi oluşturarak veya np.arrange ile bir çok boyut ekleyebilirsiniz. Aynı şeyi oluşturmak için iki yolda aşağıda:


In [3]:
w = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])
w

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
y = np.arange(8).reshape(2, 4)
y

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

`np.arange()` Python `range()`‘e benzer şekilde çalışır (0 dan başlayan ve 1 ile artış gösteren bir dizi sayı oluşturarak). bir aralığa dönmek yerine, bir diziye dönüyor. `.reshape()` [array metodu](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.reshape.html) ile başlangıçtaki 8 elemanlı diziyi yeniden şekillendirerek 4 parçalı iki dizi oluşturma avantajına sahibiz. 

Bununla şimdi kolayca uğraşabilirsiniz. Dizi oluşturmak için `.reshape()` ve `arange()` sık kullanılan yollardır. 


## Element-wise and Aggregator fonksiyonlar

Şu ana kadar Numpy’nin temel veri yapısını gördünüz, bu paketin birkaç fonksiyonelliğini daha tanıtabiliriz. Numpy’nin birincil değeri temel Python’a göre karmaşık aritmetikleri yapabilmesidir. Numpy bu hesaplamaları iki yolla yapabilmenize izin verir: element-wise fonksiyonlar dizi elemanlarının herbiri üzerinde çalışır ve sonra onları yeni diziye çevirir, aggregator fonksiyonlar ise diziyi tek bir değere işler.

Basit bir dizi ile bunu deneyelim ve hangisi mümkün görelim. Önce, bazı element-wise fonksiyonları görelim:

In [5]:
x = np.array([0, 1, 2, 3])

# Square each value.
print(np.square(x))

# Square root of each value.
print(np.sqrt(x))

# Cosine of each value.
print(np.cos(x))


[0 1 4 9]
[0.         1.         1.41421356 1.73205081]
[ 1.          0.54030231 -0.41614684 -0.9899925 ]


Gördüğünüz gibi bu metot girdi dizi ile aynı uzunlukta diziyi çalıştırıyor, Python fonksiyonu map() gibi. Dizideki her bir elemanı dönüştürmek istediğinizde ve bütün sonuçları toplamak istediğinizde element-wise fonksiyonunları kullanırsınız. 
Şimdi de aggregator fonksiyonları için bir örnek izleyelim, dizinin her bir elemanını toplayarak tek bir değer elde edelim:

In [6]:
x = np.array([0, 1, 2, 3])

# Find the maximum value.
print(np.max(x))

# Find the minimum value.
print(np.min(x))

# Find the mean of the input array.
print(np.mean(x))

# Find the standard deviation of the input array.
print(np.std(x))

3
0
1.5
1.118033988749895


Kaynak fonksiyonları bir dizi çalıştırmak yerine tek bir değer çalıştırıyor. Bu tam olarak kaynağın yaptığıdır. Bir çok veri değerini alır, bir kurala göre onları bir tek değerde yoğunlaştırır. `np.min()`  kendisine verilen değerlerin en küçüğünü döndürür, `np.mean()` ortalamasını. 

Bunlar Numpy nin bazı temel fonksiyonları, ama çok daha fazlası var. Ders boyunca paketi kullanmaya devam edeceğiz ve daha fazlasını öğreneceğiz. Eğer daha fazlasını şimdi öğrenmek istiyorsanız temel [NumPy dökümantasyonuna](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html) bakabilirsiniz. 
